"""add rejection_reason to loan

Revision ID: 3ba51d36d89d
Revises: 8524e2b1165a
Create Date: 2026-03-10 13:09:56.154122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3ba51d36d89d"
down_revision: Union[str, Sequence[str], None] = "8524e2b1165a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loans", sa.Column("rejection_reason", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loans", "rejection_reason")
    # ### end Alembic commands ###
