"""add_details_to_audit_logs

Revision ID: 4d889cf751ed
Revises: a1b2c3d4e5f6
Create Date: 2026-03-22 19:24:08.668306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d889cf751ed'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###
