"""Add settings tables, remove fields from program and student

Revision ID: 847926dccc84
Revises: 7cff7323d7fd
Create Date: 2026-03-03 20:33:30.462261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "847926dccc84"
down_revision: Union[str, Sequence[str], None] = "7cff7323d7fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_hours_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("required_hours", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.add_column(
        "programs",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.drop_column("programs", "faculty")
    op.drop_column("programs", "total_required_hours")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "programs",
        sa.Column(
            "total_required_hours", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column("faculty", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("programs", "updated_at")
    op.drop_table("system_settings")
    op.drop_table("social_hours_config")
    # ### end Alembic commands ###
